name: Self-Hosted Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  self_hosted_job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | sed -n "1"p

      - name: Print working directory
        run: pwd
